### 선형회귀 모형

 - 독립변수 $x$에서 종속변수 $y$를 예측
 
     $\hat{y}$ = $w_1$$x_1$ + $\cdots$ + $w_N$$x_N$
     
     $\hat{y}$ = $w^T$$x$

### 인공신경망(artificial neural network)

 - 선형회귀 모형의 단점 : 현실데이터를 잘 예측하지 못할 수 있지만, 많이 쓰이고 있음
 - 행렬과 벡터의 곱으로 나타낼 수 있다.
 
     $\hat{y}$ = $Wx$
    

### 제곱합(sum of squares)

 - 벡터의 모든 값을 더한 후에 제곱
 - 벡터의 내적을 사용하여 $x^T$$x$ 로 쓸 수 있다.

### 행렬과 행렬의 곱셈

 -  $C = AB$ $c_i$$_j$ = $a_i^T$$b_j$
 
 
 $A$$\in$ $R^N$$^\times$$^L$ , $B\in$$R^L$$^\times$$^M$ $\rightarrow$ $AB\in$$R^N$$^\times$$^M$
 
 

In [0]:
A = np.arange(1,7).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
B = np.arange(1, 7).reshape(3, 2)
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
C = A@B
C

array([[22, 28],
       [49, 64]])

In [0]:
np.dot(A,B) 

array([[22, 28],
       [49, 64]])

In [0]:
D = B @ A
D

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [1]:
A@B != B@A

NameError: ignored

In [0]:
A = np.arange(1,4)
B = np.array([[4,7],[5,8],[6,9]])
A @ B

array([32, 50])

In [0]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)

(array([[1, 2],
        [3, 4]]), array([[5, 6],
        [7, 8]]))

In [0]:
a@b

array([[19, 22],
       [43, 50]])

In [0]:
b@a

array([[23, 34],
       [31, 46]])

In [0]:
A = np.arange(1,7).reshape(3,2)
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
A.T@A

array([[35, 44],
       [44, 56]])

In [0]:
A@A.T

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [0]:
x = np.array([[1],[2],[3]])
x

array([[1],
       [2],
       [3]])

In [0]:
x.T@x #스칼라

array([[14]])

In [0]:
x@x.T #정방행렬

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

### 교환법칙과 분배법칙

 - $AB$ $\neq$ $BA$ 
 - $A(B+C) = AB+AC$
 - $(A+B)C = AC+BC$

In [0]:
A = np.arange(1,5).reshape(2,2)
B = np.arange(5,9).reshape(2,2)
C = np.arange(9,5,-1).reshape(2,2)

In [0]:
A@B

array([[19, 22],
       [43, 50]])

In [0]:
B@A

array([[23, 34],
       [31, 46]])

In [0]:
A@(B+C)

array([[42, 42],
       [98, 98]])

In [0]:
(A+B)@C

array([[110,  96],
       [174, 152]])

In [0]:
A@C+B@C

array([[110,  96],
       [174, 152]])

In [0]:
A@B+A@C

array([[42, 42],
       [98, 98]])

#### 전치연산도 분배가 성립하지만 곱셈의 경우 위치가 바뀐다.

In [0]:
(A+B).T

array([[ 6, 10],
       [ 8, 12]])

In [0]:
A.T+B.T

array([[ 6, 10],
       [ 8, 12]])

In [0]:
(A@B).T

array([[19, 43],
       [22, 50]])

In [0]:
A.T@B.T

array([[23, 31],
       [34, 46]])

In [0]:
B.T@A.T

array([[19, 43],
       [22, 50]])

1) 길이가 같은 열벡터 $1_N\in$$R^N$ 와 행벡터 $x\in$$R^N$의 곱은 행벡터 $x$를 반복하여 가지는 행렬과 같은지 보자

In [0]:
x = np.arange(1,4).reshape(3,1)
x

array([[1],
       [2],
       [3]])

In [0]:
y = np.arange(1,4).reshape(1,3)
y

array([[1, 2, 3]])

In [0]:
X = x@y
X

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

2) 행렬 $X(X\in$$R^N$$^\times$$^M)$가 있을 때, 이 행렬의 각 열의 평균으로 이루어진 벡터 $\overline{x}(\overline{x}$$\in$$R^M)$가 다음과 같음을 보자

3) 행렬 $X(X\in$$R^N$$^\times$$^M)$은 동일한 벡터 $\overline{x}$$^T$를 $N$개 누적하여 만든 행렬이다 즉, 각 열의 모든 값이 그 열의 평균으로 이루어진 행렬이다. 이때 $\overline{X}$가 다음과 같음을 보자

4) 다음 코드를 실행하면 붓꽃 전체 데이터를 모두 벡터로 반환하여 하나의 Numpy 행렬 X를 만든다. 

    from sklearn.datasets import load_iris
    X = load_iris().data
    
   이 데이터로 행렬 $\overline{X}$의 값을 계산하라. 이 행렬은 첫번째 열의 값이 모두 같은 값으로 붓꽃의 꽃받침의 길이(sepal length)의 평균이고, 두 번째 열의 값이 모두 같은 값으로 붓꽃의 꽃받침의 폭(sepal width)의 평균, 이런 식으로 계산된 행렬이다. 

In [0]:
from sklearn.datasets import load_iris
X = load_iris().data
N = X.shape[0]
ones = np.ones(N).reshape(-1,1)

X_bar = ((ones@ones.T)@X)/N
X_bar[:5]

array([[5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333]])

### 곱셈의 연결

 - 연속된 행렬의 곱셈은 계산순서를 임의로 해도 상관없다. 
 
 $ABC = (AB)C = A(BC)$
 
 $ABCD = ((AB)C)D = (AB)(CD) = A(BCD) = A(BC)D$

 - 다음 행렬의 곱셈을 순서를 바꾸어 두 가지 방법으로 해본다. 

In [0]:
a = np.array([1,2])
b = np.arange(1,5).reshape(2,2)
c = np.arange(5,7).reshape(2,1)

In [0]:
a@b@c == (a@b)@c , (a@b)@c == a@(b@c)


(array([ True]), array([ True]))

### 항등행렬의 곱셈

 - $AI = IA = A$

In [0]:
A = np.arange(1,5).reshape(2,2)
I = np.eye(2)

In [0]:
A@I

array([[1., 2.],
       [3., 4.]])

In [0]:
I@A

array([[1., 2.],
       [3., 4.]])

In [0]:
A

array([[1, 2],
       [3, 4]])

In [0]:
s = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
np.linalg.det(s)

4.0