### 행렬식(determinant)

 - det(A) or $|A|$ 라는 기호로 표기한다.
 - 재귀적인 형태의 정의!
 
     $det(|a|) = a$
     
     $det(A) = \sum^N_{i=1}$ $\{(-1)^{i+j_0}M_{ij_0}\}a_{ij_0}$

In [0]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(A)

- 2x2 행렬의 행렬식

    $(ad-bc)$
    
- 3x3 행렬의 행렬식

    $(aei + bfg + cdh - ceg - bdi - afh)$

### 행렬식의 성실

- 전치 행렬의 행렬식은 원레의 행렬의 행렬식과 같다.

    $det(A^T) = det(A)$

- 항등 행렬의 행렬식은 1이다.

    $det(I) = I$

- 두 행렬의 곱의 행렬식은 각 행렬의 행렬식의 곱과 같다.

    $det(AB) = det(A)det(B)$
    
- 역행렬 $A_-1$ 은 원래의 행렬 $A$ 와 다음 관계를 만족하는 정방행렬을 말한다. $I$는 항등행렬이다.

    $A^{-1}A =AA^{-1} = I$
    
- 역행렬의 행렬식은 원래의 행렬의 행렬식의 역수와 같다.

    $det(A^{-1}) =\frac{1}{det(A)}$
    
- 위의 식은 역행렬의 여인수 전개식을 사용하여 증명할 수 있다. 

    $det(A)det(A^{-1}) = det(I) = I$

In [0]:
N = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
N

In [0]:
np.trace(N)

In [0]:
M = np.arange(1, 5).reshape(2, 2)
M

In [0]:
np.linalg.det(M)

### 선형 연립방정식과 역행렬
 
   - $\rightarrow$ 연립일차방정식
   
   $A_X = b$
   
   - $A$ : 계수행렬(conefficient matrix)
   - $x$ : 미지수벡터(unknown vector)
   - $b$ : 상수벡터(constant vector)
   
   
   - $A,x,b$가 스칼라 실수일 때, 
       $x = \frac{b}{A}$ 이지만, 벡터는 나눗셈이 없으므로 비슷한 구조인 '역행렬'함수 이용

### 역행렬

 - $A^{-1}A = AA^{-1} = I$
 - 가역행렬 / 비가역행렬(singluar mextrix)

#### 대각행렬의 역행렬

### 역행렬의 성질

 - 전치행렬의 역행렬은 역행렬의 전치행렬과 같다. 따라서 대칭 행렬의 역행렬도 대칭행렬이다. 
 
     $(A^T)^{-1} = (A^{-1})^T$
     
 - 두개 이상의 정방행렬의 곱은 같은 크기의 정방행렬이 되는데 이러한 행렬의 곱의 역행렬은 다음 성질이 성립한다.
 
     $(AB)^{-1} = B^{-1}A^{-1}$
     
     $(ABC)^{-1} = C^{-1}B^{-1}A^{-1}$

### 역행렬의 계산
- $A^{-1} = \frac{1}{det(A)}C^T$

In [0]:
d = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])

np.linalg.inv(d)

In [0]:
d = np.array([[0, 1], [2, 3]])
d_inv = np.linalg.inv(d)
d_inv

In [0]:
d.dot(d_inv)

### 역행렬에 대한 정리

 1. 셔먼-모리슨 공식
 
     $(A+uv^T)^{-1} = A^{-1}-$$\frac{A^{-1}uv^TA^{-1}}{1+v^TA{-1}u}$
 
 2. 우드베리 공식
 
     $(A+UCV)^{-1} = A^{-1}-A^{-1}(C^{-1}+VA^{-1}U)^{-1}VA^{-1}$
 
 3. 분할행렬의 역행렬
 

In [0]:
A = np.arange(1, 5).reshape(2, 2)
Ainv = np.linalg.inv(A)
Ainv

### 역행렬과 선형 연립방정식의 해

$Ax = b$

$A^{-1}Ax = A^{-1}b$

$Ix = A^{-1}b$

$x = A^{-1}b$


In [0]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])
A

In [0]:
Ainv = np.linalg.inv(A)
Ainv

In [0]:
b = np.array([[2], [2], [3]])
b

In [0]:
x = Ainv @ b
x

In [0]:
A @ x - b

In [0]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

### 선형 연립방정식과 선형 예측모형

- 데이터가 미지수의 갯수만큼 필요함 

 $Xw = y$
 
 $w = X^{-1}y$
 
  - X의 역행렬이 존재해야 풀 수 있다.

In [0]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0, 4, 5, 6]]  # 'CRIM','NOX','RM','AGE'
b = y[:4]

In [0]:
A

In [0]:
b

In [0]:
Ainv = np.linalg.inv(A)
x = np.dot(Ainv, b)
x

In [0]:
x, resid, rank, s = np.linalg.lstsq(X, y)
x

### 미지수와 방정식의 수

1. 방정식의 수가 미지수의 수와 같다. $(N = M)$
2. 방정식의 수가 미지수의 수보다 적다. $(N < M)$

 - 정보 / 힌트가 곧 방정식의 갯수
 - 문제를 풀 수가 없다.
 
3. 방정식의 수가 미지수의 수보다 많다. $(N > M)$

 - $x_1 +x_2+2x_3 = 4$
 - 답이 존재하지 않는 경우가 일반적인 경우
 - 그럼... 일반적으로 다 데이터를 못 푸는 건가??? 
  $\rightarrow$ 최소자승문제로 문제를 바꿈!!! 

### 최소자승문제

 - $e = Ax -b$
  : 똑같지는 않아도 최소한 비슷한 답을 찾을 수는 있지 않을까?
 

### 벡터의 놈(norm)을 최소화! 

 $e^Te = \|e\|^2 = (Ax-b)^T(Ax-b)$
 
 $x =arg min_x e^Te = arg min_x (Ax-b)^T(Ax-b)$ 

### 최적화...  -> 벡터와 행렬의 미분!

$x = ((A^TA)^{-1}A^T)b$

### 의사 역행렬(pseudo inverse)

 $A^+ = (A^TA)^{-1}A^T$
 
 $x = A^+b$

In [0]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1], [1, 1, 2]])
A

In [0]:
b = np.array([[2], [2], [3], [4.1]])
b

In [0]:
Apinv = np.linalg.inv(A.T@A)@A.T
Apinv

In [0]:
x = Apinv @ b
x

In [0]:
A@x

In [0]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

In [0]:
# e = Ax-b 의 제곱합, 놈의 제곱값
resid, np.linalg.norm(A@x-b)**2

#### 선형 예측모형 $Xw = \hat{y}$ 로 풀었을 때의 가중치벡터 $w$를 최소자승 방법으로 구하라

In [0]:
from sklearn.datasets import load_boston
boston = load_boston()

X = boston.data
y = boston.target

In [0]:
x, resid, rank, s = np.linalg.lstsq(X, y)
x

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([-9.28965170e-02,  4.87149552e-02, -4.05997958e-03,  2.85399882e+00,
       -2.86843637e+00,  5.92814778e+00, -7.26933458e-03, -9.68514157e-01,
        1.71151128e-01, -9.39621540e-03, -3.92190926e-01,  1.49056102e-02,
       -4.16304471e-01])

In [0]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1], [1, 1, 2]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [0]:
b = np.array([[2], [2], [3], [4.1]])
b

array([[2. ],
       [2. ],
       [3. ],
       [4.1]])

In [0]:
Apinv = np.linalg.inv(A.T @ A)@ A.T
Apinv

array([[ 0.33333333, -1.        ,  0.33333333,  0.33333333],
       [ 0.5       ,  1.        ,  0.        , -0.5       ],
       [-0.5       ,  0.        ,  0.        ,  0.5       ]])

In [0]:
x = Apinv @ b
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [0]:
A@x

array([[1.98333333],
       [2.        ],
       [3.03333333],
       [4.08333333]])

In [0]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [0]:
resid, np.linalg.norm(A@x - b)**2

(array([0.00166667]), 0.0016666666666666698)