### 고윳값 분해

In [0]:
# 연습문제 3.3.1

In [0]:
B = np.array([[2,3],[2,1]])

lambda1 = 4
# v1 = np.array([3/np.sqrt(13), 2/np.sqrt(13)])
v1 = np.array([[3],[2]])

lambda2 = -1
v2 = np.array([-1/np.sqrt(2), 1/np.sqrt(2)])
# v2 = np.array([[-1],[1]])

# print(B @ v1, "\n", lambda1 * v1)
print(np.array_equal(B@v1, lambda1*v1))
print(np.array_equal(B@v2, lambda2*v2))

True
True


### Numpy를 사용한 고유분해

In [0]:
# eig()

A = np.array([[1,-2],[2,-3]])
w1, v1 = np.linalg.eig(A)
print(w1,"\n", v1)

[-0.99999998 -1.00000002] 
 [[0.70710678 0.70710678]
 [0.70710678 0.70710678]]


In [0]:
B = np.array([[2,3],[2,1]])
w2, v2 = np.linalg.eig(B)
print(w2, "\n", v2)

[ 4. -1.] 
 [[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [0]:
C = np.array([[0,-1],[1,0]])
w3, v3 = np.linalg.eig(C)
print(w3, "\n" ,v3) #복소수 계산

[0.+1.j 0.-1.j] 
 [[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]


In [0]:
D = np.array([[2,1],[1,2]])
w4, v4 = np.linalg.eig(D)
print(w4,"\n",v4)

[3. 1.] 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [0]:
E = np.array([[2,3],[2,1]])
w5, v5 = np.linalg.eig(E)
print(w5,"\n",v5)

[ 4. -1.] 
 [[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [0]:
F = np.array([[1,1],[0,1]])
w6, v6 = np.linalg.eig(F)
print(w6,"\n",v6)

[1. 1.] 
 [[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16]]


### 대각화

In [0]:
v2

array([[ 0.83205029, -0.70710678],
       [ 0.5547002 ,  0.70710678]])

In [0]:
v2_inv = np.linalg.inv(v2)
v2_inv

array([[ 0.72111026,  0.72111026],
       [-0.56568542,  0.84852814]])

In [0]:
v2 @ np.diag(w2) @ v2_inv

array([[2., 3.],
       [2., 1.]])

In [0]:
ww,VV = np.linalg.eig(np.array([[2,3],[2,1]]))
VV_inv = np.linalg.inv(VV)
VV_inv

array([[ 0.72111026,  0.72111026],
       [-0.56568542,  0.84852814]])

In [0]:
vv @ np.diag(ww) @ vv_inv

array([[2., 3.],
       [2., 1.]])

In [0]:
bb, vv2 = np.linalg.eig(np.array([[1,1],[0,1]]))
print(vv2)

[[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16]]


In [0]:
vv2_inv = np.linalg.inv(vv2)
vv2_inv

array([[1.00000000e+00, 4.50359963e+15],
       [0.00000000e+00, 4.50359963e+15]])

In [0]:
vv2 @ np.diag(bb) @ vv2_inv

array([[1., 0.],
       [0., 1.]])

In [0]:
print(np.linalg.matrix_rank(vv2))

1


In [0]:
W, S = np.linalg.eig(np.array([[2,5],[3,4]]))
print(S)
S_inv = np.linalg.inv(S)
print(S_inv)
print(np.diag(W))
print(S @ np.diag(W) @ S_inv)
print(np.linalg.matrix_rank(S))

[[-0.85749293 -0.70710678]
 [ 0.51449576 -0.70710678]]
[[-0.72886899  0.72886899]
 [-0.53033009 -0.88388348]]
[[-1.  0.]
 [ 0.  7.]]
[[2. 5.]
 [3. 4.]]
2
