### 특잇값 분해

In [0]:
from numpy.linalg import svd

In [0]:
A = np.array([[3,-1],[1,3],[1,1]])
U, S, VT = svd(A)

In [0]:
U

array([[-4.08248290e-01,  8.94427191e-01, -1.82574186e-01],
       [-8.16496581e-01, -4.47213595e-01, -3.65148372e-01],
       [-4.08248290e-01, -1.94289029e-16,  9.12870929e-01]])

In [0]:
S

array([3.46410162, 3.16227766])

In [0]:
VT

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [0]:
# 다이어분할을 지정하는 1 == 대각화를 실행할 때 한 칸 올려서 실행해라.

np.diag(S,1)[:,1:]

array([[3.46410162, 0.        ],
       [0.        , 3.16227766],
       [0.        , 0.        ]])

In [0]:
U @ np.diag(S,1)[:,1:] @ VT

array([[ 3., -1.],
       [ 1.,  3.],
       [ 1.,  1.]])

In [0]:
U2, S2, VT2 = svd(A, full_matrices=False)

In [0]:
U2

array([[-4.08248290e-01,  8.94427191e-01],
       [-8.16496581e-01, -4.47213595e-01],
       [-4.08248290e-01, -1.94289029e-16]])

In [0]:
S2

array([3.46410162, 3.16227766])

In [0]:
VT2

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [0]:
U2 @ np.diag(S2) @ VT2

array([[ 3., -1.],
       [ 1.,  3.],
       [ 1.,  1.]])

In [0]:
B = np.array([[3,2,2],[2,3,-2]])
C = np.array([[2,4],[1,3],[0,0],[0,0]])

In [0]:
U3, S3, VT3 = svd(B)
U4, S4, VT4 = svd(B, full_matrices=False)

In [0]:
U3

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [0]:
U4

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [0]:
np.diag(S3,-1)[1:,:]

array([[5., 0., 0.],
       [0., 3., 0.]])

In [0]:
S4

array([5., 3.])

In [0]:
VT3

array([[-7.07106781e-01, -7.07106781e-01, -5.55111512e-17],
       [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01],
       [-6.66666667e-01,  6.66666667e-01,  3.33333333e-01]])

In [0]:
VT4

array([[-7.07106781e-01, -7.07106781e-01, -5.55111512e-17],
       [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01]])

In [0]:
np.diag(S3)

array([[5., 0.],
       [0., 3.]])

In [0]:
U3 @ np.diag(S3,-1)[1:,:] @ VT3

array([[ 3.,  2.,  2.],
       [ 2.,  3., -2.]])

In [0]:
U4 @ np.diag(S4) @ VT4

array([[ 3.,  2.,  2.],
       [ 2.,  3., -2.]])

In [0]:
U5, S5, VT5 = svd(C)
U6, S6, VT6 = svd(C, full_matrices=False)

In [0]:
print(U5)
print(np.diag(S5,2)[:,2:])
print(VT5)
print(U5 @ np.diag(S5,2)[:,2:]@VT5)

[[-0.81741556 -0.57604844  0.          0.        ]
 [-0.57604844  0.81741556  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
[[5.4649857  0.        ]
 [0.         0.36596619]
 [0.         0.        ]
 [0.         0.        ]]
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
[[2. 4.]
 [1. 3.]
 [0. 0.]
 [0. 0.]]


In [0]:
print(U6)
print(np.diag(S6))
print(VT6)
print(U6 @ np.diag(S6) @ VT6)

[[-0.81741556 -0.57604844]
 [-0.57604844  0.81741556]
 [ 0.          0.        ]
 [ 0.          0.        ]]
[[5.4649857  0.        ]
 [0.         0.36596619]]
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
[[2. 4.]
 [1. 3.]
 [0. 0.]
 [0. 0.]]
