### 전역 최적화 문제

 - 컨벡스 문제 (딥러닝을 제외한 머신러닝에서 활용)
  : 2차 도함수가 양수
 
     $\frac{\partial^2f}{\partial x^2} \geq 0$
     
      - 전역 최저점이 항상 존재한다. 

---
### 제한 조건이 있는 최적화 문제 

 1) 등식 제한 조건
 
  - $x* = arg min_x f(x)$
  - $x \in R^N$
  - $g_j(x) = 0 (j = 1, ... , M)$
  
  
  * 목적함수 
  
   $f(x) + \Sigma^M_{j=1}\lambda_j g_j (x)$
 
   $f(x) + \lambda g(x)$
   
   $\rightarrow$ fmin_slsqp()


 2) 부등식 제한 조건
 
  - $x* = arg min_x f(x)$
  - $x \in R^N$
  - $g_j(x) \leq 0 (j = 1, ... , M)$
  
  * 목적함수
  
   $f(x) + \Sigma^M_{j=1}\lambda_j g_j (x)$
   
#### KKT (Karuch-Kuhn-Tucker) 조건
   
1) 모든 독립변수 $x_1,x_2,x_3,...,X_N$에 대한 미분값이 0이다
    
$\frac{\partial h(x,\lambda)}{\partial x_1} = 0$
    
2) 모든 라그랑주 승수 $\lambda_1, ... , \lambda_M$과 제한 조건 부등식 ($\lambda$에 대한 미분값)의 곱이 0이다. 
    
$\lambda_j \cdot \frac{\partial h(x,\lambda)}{\partial \lambda_j} = \lambda_j \cdot g_j = 0$
    
3) 라그랑주 승수는 음수가 아니어야 한다. 
       
$\lambda_j \geq 0$

In [69]:
def f1array(x):
    return x[0]**2 + x[1] ** 2


def eq_constraint(x):
    return x[0]+x[1]-1


sp.optimize.fmin_slsqp(f1array, np.array([1, 1]), eqcons=[eq_constraint])

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 0.5000000000000002
            Iterations: 2
            Function evaluations: 8
            Gradient evaluations: 2


array([0.5, 0.5])

#### 라그랑주 승수의 의미

 - $\lambda_i \neq 0$
 
 ex) 
 
  $f = x_1^2 + x_2^2$
  
  $x* = (0,0)$
  
  $g = x_1 + x_2 - 1 = 0$ 
  
      *제한조건 $h = x_1^2 + x_2^2 + \lambda(x_1+x_2-1)$
  
  $x* = (\frac{1}{2},\frac{1}{2})$
      
      * 최적화하려는 목적함수가 다르기 때문에 답이 다를 수 밖에 없음 !
      * $\lambda$가 0이면 등식제한조건이 무용지물. 


In [70]:
def f2(x):
    return np.sqrt((x[0] - 4)**2 + (x[1]-2)**2)

k = 1
def ieq_constraint(x):
    return np.atleast_1d(k-np.sum(np.abs(x)))

sp.optimize.fmin_slsqp(f2, np.array([0,0]), ieqcons=[ieq_constraint])

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 3.6055512804550336
            Iterations: 11
            Function evaluations: 77
            Gradient evaluations: 11


array([9.99999982e-01, 1.79954011e-08])

In [73]:
def f2(x):
    return np.sqrt((x[0] - 4)**2 + (x[1]-2)**2)

k = 2
def ieq_constraint(x):
    return np.atleast_1d(k-np.sum(np.abs(x)))

sp.optimize.fmin_slsqp(f2, np.array([0,0]), ieqcons=[ieq_constraint])

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 2.8284287493322235
            Iterations: 8
            Function evaluations: 38
            Gradient evaluations: 8


array([1.9978564, 0.0021436])

In [75]:
def f2(x):
    return np.sqrt((x[0] - 4)**2 + (x[1]-2)**2)

k = 0.5
def ieq_constraint(x):
    return np.atleast_1d(k-np.sum(np.abs(x)))

sp.optimize.fmin_slsqp(f2, np.array([0,0]), ieqcons=[ieq_constraint])

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 4.031128897766439
            Iterations: 12
            Function evaluations: 78
            Gradient evaluations: 12


array([4.99999937e-01, 6.34692395e-08])